package com.apica.backend.integrationservice.model;

import java.io.Serializable;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import io.swagger.annotations.ApiModelProperty;

@Document(collection = "integrationprofiles")
public class IntegrationProfile implements Serializable {
  
  @ApiModelProperty(notes = "The database generated ID")
  @Id
  private String id;
  @ApiModelProperty(notes = "The customerId in ASM.")
  private String customerId;
  @ApiModelProperty(notes = "The customerId in ASM.")
  private String userId;
  private Boolean readOnly;
  private Boolean shared;
  @ApiModelProperty(notes = "The name of the back-end platform")
  private String platformId;
  @ApiModelProperty(notes = "A logical name for the profile")
  private String name;
  @ApiModelProperty(notes = "The URL for the back-end system")
  private String url;
  @ApiModelProperty(notes = "The account often used for authentication")
  private String account;
  @ApiModelProperty(notes = "The application name in the back-end system")
  private String application;
  @ApiModelProperty(notes = "The application id. Generated by the system")
  private String applicationId;
  @ApiModelProperty(notes = "Authentication properties for the platform")
  private Authentication authentication;
  private String description;
  private final static long serialVersionUID = -277276843225388360L;

  /**
   * No args constructor for use in serialization
   *
   */
  public IntegrationProfile() {}

  /**
   *
   * @param shared
   * @param description
   * @param readOnly
   * @param platformId
   * @param userId
   * @param url
   * @param application
   * @param customerId
   * @param name
   * @param id
   * @param applicationId
   * @param account
   * @param authentication
   */
  public IntegrationProfile(String id, String customerId, String userId, Boolean readOnly,
      Boolean shared, String platformId, String name, String url, String account,
      String application, String applicationId, Authentication authentication, String description) {
    super();
    this.id = id;
    this.customerId = customerId;
    this.userId = userId;
    this.readOnly = readOnly;
    this.shared = shared;
    this.platformId = platformId;
    this.name = name;
    this.url = url;
    this.account = account;
    this.application = application;
    this.applicationId = applicationId;
    this.authentication = authentication;
    this.description = description;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IntegrationProfile withId(String id) {
    this.id = id;
    return this;
  }

  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public IntegrationProfile withCustomerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public IntegrationProfile withUserId(String userId) {
    this.userId = userId;
    return this;
  }

  public Boolean getReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public IntegrationProfile withReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

  public Boolean getShared() {
    return shared;
  }

  public void setShared(Boolean shared) {
    this.shared = shared;
  }

  public IntegrationProfile withShared(Boolean shared) {
    this.shared = shared;
    return this;
  }

  public String getPlatformId() {
    return platformId;
  }

  public void setPlatformId(String platformId) {
    this.platformId = platformId;
  }

  public IntegrationProfile withPlatformId(String platformId) {
    this.platformId = platformId;
    return this;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IntegrationProfile withName(String name) {
    this.name = name;
    return this;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public IntegrationProfile withUrl(String url) {
    this.url = url;
    return this;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public IntegrationProfile withAccount(String account) {
    this.account = account;
    return this;
  }

  public String getApplication() {
    return application;
  }

  public void setApplication(String application) {
    this.application = application;
  }

  public IntegrationProfile withApplication(String application) {
    this.application = application;
    return this;
  }

  public String getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(String applicationId) {
    this.applicationId = applicationId;
  }

  public IntegrationProfile withApplicationId(String applicationId) {
    this.applicationId = applicationId;
    return this;
  }

  public Authentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(Authentication authentication) {
    this.authentication = authentication;
  }

  public IntegrationProfile withAuthentication(Authentication authentication) {
    this.authentication = authentication;
    return this;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public IntegrationProfile withDescription(String description) {
    this.description = description;
    return this;
  }

}
